name: CI

on:
  push:
    branches: 
      - master
      - feature/*      
  pull_request:
    branches: 
      - master    
env:
  ALICE_TESTNET_ADDRESS: ${{ secrets.ALICE_TESTNET_ADDRESS }}
  ALICE_TESTNET_WALLET_ID: ${{ secrets.ALICE_TESTNET_WALLET_ID }}
  BOB_TESTNET_ADDRESS: ${{ secrets.BOB_TESTNET_ADDRESS }}
  BOB_TESTNET_WALLET_ID: ${{ secrets.BOB_TESTNET_WALLET_ID }}      
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Validate Specification
        uses: 2qx/codegen-docker-action@v1
        with:
          args: |
            validate -i swagger/v1/api.yml
      - name: Generate Mock Client
        uses: 2qx/codegen-docker-action@v1
        with:
          args: |
            generate -i swagger/v1/api.yml -g typescript-node -o generated/client/typescript-mock
      - name: Generate Server
        uses: 2qx/codegen-docker-action@v1
        with:
          args: |
            generate -i swagger/v1/api.yml -g typescript-express-server -o generated/serve
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: Update generated
  format:
    needs: [ generate ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Format
        run: |
          yarn
          yarn format
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: Apply formatting changes
  test_linux:
    name: ${{ matrix.os }} (${{ matrix.browser }})
    needs: [ format ]
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        browser: [chromium, firefox, webkit]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: docker/build.sh
    - uses: microsoft/playwright-github-action@v1
    - run: npm install
    - run: npm run test
    - run: npm run build
    - run: npm run test:browser
      env:
        BROWSER: ${{ matrix.browser }}
  coverage:
    needs: [ test_linux ]
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '12'
    - run: docker/build.sh        
    - run: npm install
    - uses: paambaati/codeclimate-action@v2.5.7
      env:
        CC_TEST_REPORTER_ID: cf454b72ccba2f9ed854092c9c9f89b8d3dbae7417f7ed0d75421e53a404b824
      with:
        coverageCommand: npm run coverage
        debug: true